### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by moorepants** [conda-forge/pyshtools-feedstock#2]
This will likely require complication with flang. An example repository where we have this working for windows with flang is: https://github.com/conda-forge/slycot-feedstock

**Comment by MarkWieczorek** [comment]
Is there a good example you could point me to for making conda-forge builds for windows? (real basic, I don't know if these use the same meta file, or something different). We have windows builds on pypi made using appveyor, so this script might help in getting it done: https://github.com/SHTOOLS/build-shtools/blob/master/appveyor.yml

**Comment by moorepants** [comment]
We build slyclot for windows using flang here: https://github.com/conda-forge/slycot-feedstock but make use of scikit-build in slycot to help things along.

**Comment by xiaojingdounaodan** [comment]
when i used this pacakge in ggtools on windows，there is a problem "'centralmeridian' is an invalid keyword argument for _SHTOOLS.Curve2Mask()"，why?

**Comment by MarkWieczorek** [comment]
Hi @xiaojingdounaodan , could you open an issue on the main https://github.com/SHTOOLS/SHTOOLS project, and provide some output so that we can help debug this?

**Comment by moorepants** [comment]
Closed with #30
