### ISSUE TITLE
The conda built binaries may need to be GPL licensed, instead of the license of SHTOOLS

### ISSUE THREAD

**Issue by moorepants** [conda-forge/pyshtools-feedstock#3]
SHTOOLS links to FFTW which is GPL licensed, yet the SHTOOLS source code is licensed BSD 3-Clause. The SHTOOLS author has this to say:

https://github.com/SHTOOLS/SHTOOLS/issues/227

I'm not quite sure what this conda binary should be licensed as. Maybe it needs to be changed.

@conda-forge/help-python-c Does anyone know what is the appropriate thing to do in this case?

**Comment by beckermr** [comment]
cc @conda-forge/core

**Comment by ocefpaf** [comment]
I'm not a lawyer but I believe the conda package should be GPL in that case.

**Comment by moorepants** [comment]
Ok, I'll update this feedstock to be released under the same GPL version as FFTW but I'll include the licenses for FFTW and SHTOOLs also.

Note that it looks like there are other packages that link to FFTW that will need this change too.

https://github.com/search?l=YAML&q=org%3Aconda-forge+FFTW&type=Code

**Comment by moorepants** [comment]
According to the arguments here: https://github.com/conda-forge/openmm-feedstock/issues/24 the package only has to be licensed under at GPL compatible license. I'm still not sure I understand it completely, but erring on the side of caution would lean to keeping the GPL on this binary distribution of pyshtools.
