### ISSUE TITLE
make pygmt / gmt optional dependencies by moving to run_constraint

### ISSUE THREAD

**Issue by k-dominik** [conda-forge/pyshtools-feedstock#63]
### Comment:

`pyshtools` depends on `pygmt`/`gmt` - but in fact these are optional dependencies.

An environment without these would be lighter by the following dependencies (~40 packages, tested with 4.12 (patched pyshtools package available from [ilastik-forge/label/patched](https://anaconda.org/ilastik-forge/repo/files?type=any&label=patched))):
```
  blosc
  cftime
  curl
  dcw-gmt
  freexl
  gdal
  geotiff
  ghostscript
  giflib
  gmt
  gshhg-gmt
  hdf4
  hdf5
  icu
  json-c
  libaec
  libarchive
  libgdal-core
  libgdal-jp2openjpeg
  libglib
  libiconv
  libintl
  libkml
  libnetcdf
  librttopo
  libspatialite
  libxml2
  libzip
  lz4-c
  lzo
  minizip
  netcdf4
  pcre
  pcre2
  pygmt
  snappy
  uriparser
  xerces-c
  zlib
```
This makes it easier to include `pyshtools` in other environments that might have competing constraints on some of these.

in principle, one can do this in `meta.yaml` by

```diff
   run:
     - python
     - {{ pin_compatible('fftw') }}
     - scipy
     - matplotlib-base
     - astropy
     - xarray
     - requests
-    - gmt >=6.3.0
-    - pygmt >=0.7.0
     - cartopy >=0.18
     - pooch
     - ducc0
+  run_constrained:
+    - gmt >=6.3.0
+    - pygmt >=0.7.0
```

With that you'd still get the correct versions, but users would have to explicitly specify that they want `pygmt`, too (slight downside).

**Comment by MarkWieczorek** [comment]
If we decide to do this, we might want to also include cartopy. It is also "optional" and is used for creating map projections similar to pygmt.
